name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            java_version: 17
          - os: ubuntu-22.04
            java_version: 21
          - os: ubuntu-22.04
            java_version: 25
          - os: macos-15-intel
            java_version: 17
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6.0.1

      - uses: actions/setup-java@v5.0.0
        with:
          distribution: zulu
          java-version: ${{ matrix.java_version }}

      - uses: actions/setup-node@v6.0.0

      - run: npm install --global mermaid-filter@1.4.7

      - uses: gradle/actions/setup-gradle@v5.0.0

      - run: ./gradlew build --warning-mode all
